language: node_js
node_js:
  - "0.12"
  - "iojs"
install:
  - sudo add-apt-repository ppa:openjdk-r/ppa
  - sudo apt-get update
  - sudo apt-get install openjdk-8-jdk
  - npm install
  - bower install
  - ./node_modules/.bin/grunt release-cli
script: ./node_modules/.bin/grunt test
