language: node_js

node_js:
  - "0.12"
  - "stable"

install:
  - sudo apt-cache search oracle-java8-installer
  - sudo add-apt-repository -y ppa:openjdk-r/ppa
  - sudo apt-get update
  - sudo apt-get install -y openjdk-8-jdk
  - npm install
  - ./node_modules/.bin/tsc --version
  - ./node_modules/.bin/grunt --version

addons:
  firefox: "latest"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - ./node_modules/.bin/grunt test
  - ./node_modules/.bin/grunt test-browser-travis
